### ISSUE TITLE
Lock icon not centered with multiple monitors

### ISSUE THREAD

**Issue by owenthewizard** [owenthewizard/i3lock-next#2]
![](https://i.imgur.com/xWMX8RR.jpg)
[Reddit thread](https://www.reddit.com/r/unixporn/comments/602dl1/oc_faster_i3lockfancy_alternative/df35v4u/)

**Comment by owenthewizard** [comment]
Note to self: probably due to using the total resolution to calculate center rather than just one monitor.

**Comment by mackattack3k** [comment]
I still have this issue. I checkout out branch `multimonitor-testing` and then `make && sudo make install`.
Could it be that one of the monitors is vertical?

This is my xrandr config:
```
xrandr --output DisplayPort-1 --mode 2560x1440 --pos 2560x0 --rotate normal --output DisplayPort-2 --mode 1600x1200 --pos 5120x0 --rotate left --output DVI-0 --mode 2560x1440 --pos 0x0 --rotate normal
```

**Comment by mackattack3k** [comment]
Also, when typing in my password, the "key typed"-indicator is shown on each screen. Maybe the lock should be showed on each screen instead of the center of all?

**Comment by owenthewizard** [comment]
@mackattack3k please test the latest the multimonitor-testing branch again, the lock icon and text _should_ be working a bit better. Do note that the light/dark colors may be wrong as I haven't modified the code for that yet.

**Comment by owenthewizard** [comment]
The colors should now work as expected as well, please let me know if they do not.

**Comment by mackattack3k** [comment]
Still having issues but not quite the same outcome.
![](http://i.imgur.com/zesP2QD.jpg)

The multiple monitor branch seems to be gone so I pulled master instead.

**Comment by owenthewizard** [comment]
@mackattack3k please test again with the latest commit and let me know if the issue persists. I think it could be the rotation check because there are no issues when I use one monitor and one TV.

**Comment by mackattack3k** [comment]
It works fine on my first monitor but not on my second and third. I might have to look into my xrandr setup to see if something is off there.

**Comment by owenthewizard** [comment]
Really I'm at a loss trying to get multiple monitors to work consistently. I would be grateful if someone more familiar with libXrandr could shed some light on the proper way to iterate through monitors/screens/crtcs.

**Comment by owenthewizard** [comment]
@mackattack3k thanks to the generous work of @scherzoso this should be fixed now, please re-open this if the issue is still present.

**Comment by mackattack3k** [comment]
Just wanted to say that this has been resolved now! Thank you!

**Comment by owenthewizard** [comment]
Don't thank me, thank @scherzoso :smiley:
